// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEcPr8Pmv_ZF4f8zFHlmg-t_z_k_3jEbI',
    appId: '1:989951728763:web:d67e9c7135478697e416de',
    messagingSenderId: '989951728763',
    projectId: 'bridge-tech-advance',
    authDomain: 'bridge-tech-advance.firebaseapp.com',
    storageBucket: 'bridge-tech-advance.appspot.com',
    measurementId: 'G-DFM8VD3BRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbVs1nFKJZOw21gQGWBD3gRUpkZKQr8ww',
    appId: '1:989951728763:android:72607bf6f013f1f6e416de',
    messagingSenderId: '989951728763',
    projectId: 'bridge-tech-advance',
    storageBucket: 'bridge-tech-advance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG1ywjEBmqiE9P1XVLedhDpk8g-1kScNo',
    appId: '1:989951728763:ios:7307412c7ba04e3ee416de',
    messagingSenderId: '989951728763',
    projectId: 'bridge-tech-advance',
    storageBucket: 'bridge-tech-advance.appspot.com',
    iosClientId: '989951728763-ivok6mie48ltar2np198lsp15ko2koba.apps.googleusercontent.com',
    iosBundleId: 'com.example.urbanHiveTest',
  );
}
